use actix_web::web;

use super::handlers::{
    account_handlers, accounting_handlers, aml_handlers, auth_handlers, consent_handlers,
    credit_handlers, customer_handlers, data_rights_handlers, governance_handlers,
    payment_handlers, profile_handlers, prudential_handlers, reporting_handlers,
    retention_handlers, sanctions_handlers, two_factor_handlers, user_handlers,
};

use crate::governance::bct_audit_handlers;

pub fn configure_auth_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/auth")
            .route("/register", web::post().to(auth_handlers::register_handler))
            .route("/login", web::post().to(auth_handlers::login_handler))
            .route("/logout", web::post().to(auth_handlers::logout_handler))
            .route(
                "/2fa/enable",
                web::post().to(two_factor_handlers::enable_2fa_handler),
            )
            .route(
                "/2fa/verify",
                web::post().to(two_factor_handlers::verify_2fa_handler),
            ),
    );
}

pub fn configure_api_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1")
            .route("/profile", web::get().to(profile_handlers::get_profile))
            .route("/users", web::post().to(user_handlers::create_user_handler))
            .route("/users/{id}", web::get().to(user_handlers::get_user_handler))
            .route(
                "/users/{id}/roles",
                web::put().to(user_handlers::update_user_roles_handler),
            ),
    );
}

pub fn configure_customer_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/customers")
            .route(
                "",
                web::post().to(customer_handlers::create_customer_handler),
            )
            .route(
                "",
                web::get().to(customer_handlers::list_customers_handler),
            )
            .route(
                "/{id}",
                web::get().to(customer_handlers::get_customer_handler),
            )
            .route(
                "/{id}/kyc",
                web::get().to(customer_handlers::get_customer_kyc_handler),
            )
            .route(
                "/{id}/kyc",
                web::put().to(customer_handlers::update_kyc_handler),
            )
            .route(
                "/{id}/approve",
                web::post().to(customer_handlers::approve_kyc_handler),
            )
            .route(
                "/{id}/reject",
                web::post().to(customer_handlers::reject_kyc_handler),
            )
            // Consent routes (STORY-CONS-01)
            .route(
                "/{id}/consent",
                web::post().to(consent_handlers::grant_consent_handler),
            )
            .route(
                "/{id}/consent",
                web::delete().to(consent_handlers::revoke_consent_handler),
            )
            .route(
                "/{id}/consents",
                web::get().to(consent_handlers::list_consents_handler),
            )
            // Data rights routes (STORY-CONS-02)
            .route(
                "/{id}/data-export",
                web::get().to(data_rights_handlers::data_export_handler),
            )
            .route(
                "/{id}/data-rectification",
                web::put().to(data_rights_handlers::data_rectification_handler),
            )
            .route(
                "/{id}/data-opposition",
                web::post().to(data_rights_handlers::data_opposition_handler),
            )
            .route(
                "/{id}/data-requests",
                web::get().to(data_rights_handlers::list_data_requests_handler),
            ),
    );
}

pub fn configure_account_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/accounts")
            .route(
                "",
                web::post().to(account_handlers::create_account_handler),
            )
            .route(
                "",
                web::get().to(account_handlers::list_accounts_handler),
            )
            .route(
                "/{id}",
                web::get().to(account_handlers::get_account_handler),
            )
            .route(
                "/{id}/movements",
                web::post().to(account_handlers::create_movement_handler),
            )
            .route(
                "/{id}/movements",
                web::get().to(account_handlers::list_movements_handler),
            )
            .route(
                "/{id}/statement",
                web::get().to(account_handlers::get_statement_handler),
            ),
    );
}

pub fn configure_credit_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/loans")
            .route(
                "",
                web::post().to(credit_handlers::create_loan_handler),
            )
            .route(
                "",
                web::get().to(credit_handlers::list_loans_handler),
            )
            .route(
                "/{id}",
                web::get().to(credit_handlers::get_loan_handler),
            )
            .route(
                "/{id}/approve",
                web::post().to(credit_handlers::approve_loan_handler),
            )
            .route(
                "/{id}/disburse",
                web::post().to(credit_handlers::disburse_loan_handler),
            )
            .route(
                "/{id}/classify",
                web::post().to(credit_handlers::classify_loan_handler),
            )
            .route(
                "/{id}/payment",
                web::post().to(credit_handlers::record_payment_handler),
            ),
    );
}

pub fn configure_aml_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/transactions")
            .route(
                "",
                web::post().to(aml_handlers::create_transaction_handler),
            )
            .route(
                "",
                web::get().to(aml_handlers::list_transactions_handler),
            )
            .route(
                "/{id}",
                web::get().to(aml_handlers::get_transaction_handler),
            ),
    );
    cfg.service(
        web::scope("/api/v1/aml")
            .route(
                "/alerts",
                web::get().to(aml_handlers::list_alerts_handler),
            )
            .route(
                "/alerts/{id}",
                web::get().to(aml_handlers::get_alert_handler),
            )
            .route(
                "/investigations",
                web::post().to(aml_handlers::open_investigation_handler),
            )
            .route(
                "/investigations/{id}",
                web::get().to(aml_handlers::get_investigation_handler),
            )
            .route(
                "/investigations/{id}/notes",
                web::post().to(aml_handlers::add_note_handler),
            )
            .route(
                "/investigations/{id}/escalate",
                web::post().to(aml_handlers::escalate_investigation_handler),
            )
            .route(
                "/investigations/{id}/close",
                web::post().to(aml_handlers::close_investigation_handler),
            )
            .route(
                "/reports",
                web::post().to(aml_handlers::generate_report_handler),
            )
            .route(
                "/reports/{id}/submit",
                web::post().to(aml_handlers::submit_report_handler),
            )
            .route(
                "/freezes",
                web::post().to(aml_handlers::freeze_account_handler),
            )
            .route(
                "/freezes",
                web::get().to(aml_handlers::list_freezes_handler),
            )
            .route(
                "/freezes/{id}/lift",
                web::post().to(aml_handlers::lift_freeze_handler),
            ),
    );
}

pub fn configure_sanctions_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/sanctions")
            .route(
                "/check",
                web::get().to(sanctions_handlers::screen_name_handler),
            )
            .route(
                "/results",
                web::get().to(sanctions_handlers::list_results_handler),
            )
            .route(
                "/results/{id}",
                web::get().to(sanctions_handlers::get_result_handler),
            )
            .route(
                "/lists",
                web::get().to(sanctions_handlers::list_sanctions_lists_handler),
            )
            .route(
                "/lists/{source}",
                web::get().to(sanctions_handlers::get_list_handler),
            )
            .route(
                "/dashboard",
                web::get().to(sanctions_handlers::dashboard_handler),
            ),
    );
}

pub fn configure_prudential_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/prudential")
            .route(
                "/ratios",
                web::get().to(prudential_handlers::get_ratios_handler),
            )
            .route(
                "/ratios",
                web::post().to(prudential_handlers::calculate_ratios_handler),
            )
            .route(
                "/solvency",
                web::get().to(prudential_handlers::check_solvency_handler),
            )
            .route(
                "/tier1",
                web::get().to(prudential_handlers::check_tier1_handler),
            )
            .route(
                "/credit-deposit",
                web::get().to(prudential_handlers::check_credit_deposit_handler),
            )
            .route(
                "/concentration",
                web::get().to(prudential_handlers::check_concentration_handler),
            )
            .route(
                "/alerts",
                web::get().to(prudential_handlers::get_alerts_handler),
            ),
    );
}

pub fn configure_accounting_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/accounting")
            .route(
                "/entries",
                web::post().to(accounting_handlers::create_entry_handler),
            )
            .route(
                "/entries",
                web::get().to(accounting_handlers::list_entries_handler),
            )
            .route(
                "/entries/{id}",
                web::get().to(accounting_handlers::get_entry_handler),
            )
            .route(
                "/entries/{id}/reverse",
                web::post().to(accounting_handlers::reverse_entry_handler),
            )
            .route(
                "/ledger",
                web::get().to(accounting_handlers::get_ledger_handler),
            )
            .route(
                "/trial-balance",
                web::get().to(accounting_handlers::get_trial_balance_handler),
            )
            .route(
                "/periods/close",
                web::post().to(accounting_handlers::close_period_handler),
            )
            .route(
                "/ecl-staging",
                web::get().to(accounting_handlers::get_ecl_staging_handler),
            ),
    );
}

pub fn configure_governance_routes(cfg: &mut web::ServiceConfig) {
    governance_handlers::configure_governance_routes(cfg);
}

pub fn configure_reporting_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/reporting")
            .route(
                "/forms",
                web::get().to(reporting_handlers::list_reports_handler),
            )
            .route(
                "/forms/{id}",
                web::get().to(reporting_handlers::get_report_handler),
            )
            .route(
                "/generate",
                web::post().to(reporting_handlers::generate_report_handler),
            )
            .route(
                "/forms/{id}/validate",
                web::post().to(reporting_handlers::validate_report_handler),
            )
            .route(
                "/forms/{id}/submit",
                web::post().to(reporting_handlers::submit_report_handler),
            )
            .route(
                "/forms/{id}/acknowledge",
                web::post().to(reporting_handlers::acknowledge_report_handler),
            )
            .route(
                "/templates",
                web::get().to(reporting_handlers::list_templates_handler),
            )
            .route(
                "/ifrs9",
                web::get().to(reporting_handlers::ifrs9_handler),
            ),
    );
}

pub fn configure_payment_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/payments")
            .route(
                "/transfers",
                web::post().to(payment_handlers::create_payment_handler),
            )
            .route(
                "",
                web::get().to(payment_handlers::list_payments_handler),
            )
            .route(
                "/{id}",
                web::get().to(payment_handlers::get_payment_handler),
            )
            .route(
                "/{id}/status",
                web::get().to(payment_handlers::get_payment_status_handler),
            )
            .route(
                "/{id}/screen",
                web::post().to(payment_handlers::screen_payment_handler),
            )
            .route(
                "/{id}/submit",
                web::post().to(payment_handlers::submit_payment_handler),
            )
            .route(
                "/{id}/execute",
                web::post().to(payment_handlers::execute_payment_handler),
            )
            .route(
                "/clearing",
                web::post().to(payment_handlers::run_clearing_handler),
            ),
    );
}

pub fn configure_retention_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/admin/retention")
            .route(
                "/run",
                web::post().to(retention_handlers::run_anonymization_handler),
            )
            .route(
                "/status/{customer_id}",
                web::get().to(retention_handlers::check_retention_handler),
            ),
    );
}

pub fn configure_bct_audit_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v1/bct/audit")
            .route(
                "/entries",
                web::get().to(bct_audit_handlers::list_bct_entries_handler),
            )
            .route(
                "/entries/export",
                web::get().to(bct_audit_handlers::export_entries_handler),
            )
            .route(
                "/integrity",
                web::get().to(bct_audit_handlers::integrity_check_handler),
            ),
    );
    cfg.service(
        web::scope("/api/v1/bct/dashboard")
            .route(
                "/stats",
                web::get().to(bct_audit_handlers::dashboard_stats_handler),
            )
            .route(
                "/daily-trend",
                web::get().to(bct_audit_handlers::daily_trend_handler),
            )
            .route(
                "/suspicious",
                web::get().to(bct_audit_handlers::suspicious_handler),
            ),
    );
}
